### ISSUE TITLE
Add pyWalletConnect

### ISSUE THREAD

**Issue by antonio-fr** [WalletConnect/awesome-walletconnect#10]
In the README, Libraries or Community SDKs, you can add pyWalletConnect in the resources list. It's a Python library to add WallectConnect to a wallet.

https://github.com/bitlogik/pyWalletConnect

To my knowledge, it's the only one WCv2 implementation in Python for wallet. This library is 2 years old.

**Comment by glitch-txs** [comment]
feel free to open a PR on this.

Thanks!
